language: perl

sudo: false

perl:
    - "5.14"

cache:
    directories:
        - deps

install:
    - "cpanm --notest File::Slurp"
    - "export PATH=$PWD/.travis:$PWD/bin:$PATH"
    - "if [ ! -d deps ]; then mkdir -p deps && cd deps && source install_deps.sh && cd .. ; fi"
    - "pwd"
    - "echo $HOME"

script:
    - "shovill --version"
    - "shovill --check"
    - "shovill --help"
    - "! shovill --doesnotexist"
    - "shovill --outdir asm1 --R1 test/R1.fq.gz --R2 test/R2.fq.gz --ram 3 --cpus 2"
    - "shovill --outdir asm2 --R1 test/R1.fq.gz --R2 test/R2.fq.gz --ram 3 --cpus 2 --nocorr"
    - "shovill --outdir asm2 --R1 test/R1.fq.gz --R2 test/R2.fq.gz --ram 3 --cpus 2 --trim"
