language: perl

sudo: false

perl:
    - "5.14"

addons:
    apt:
        packages:
            - pigz
            - unzip
            
install:
    - "cpanm --notest File::Slurp"
    - "export PATH=$PWD/.travis:$PWD/bin:$PATH"
    - "mkdir -p deps && cd deps && source install_deps.sh && cd .."
    - "pwd"
    - "echo $HOME"
    - "echo $PATH"
    - "find deps -executable -type f"

script:
    - "shovill --version"
    - "shovill --check"
    - "shovill --help"
    - "! shovill --doesnotexist"
    - "shovill --outdir asm1 --R1 test/R1.fq.gz --R2 test/R2.fq.gz --ram 2 --cpus 2 --depth 25 --trim"
