language: perl

sudo: false

perl:
    - "5.26"

addons:
    apt:
        packages:
            - pigz
            - unzip
            
install:
    - "export PATH=$PWD/.travis:$PWD/bin:$PATH"
    - "mkdir -p deps && cd deps && source install_deps.sh && cd .."
    - "pwd"
    - "echo $HOME"
    - "echo $PATH"
    - "find deps -executable -type f"

script:
    - "shovill --version"
    - "shovill --check"
    - "shovill --help"
    - "! shovill --doesnotexist"
    - "shovill --outdir skesa --assembler skesa --R1 test/R1.fq.gz --R2 test/R2.fq.gz --ram 3 --trim --depth 33"
    - "grep '>' skesa/contigs.fa"
    - "shovill --outdir megahit --assembler megahit --R1 test/R1.fq.gz --R2 test/R2.fq.gz --ram 3 --nocorr"
    - "grep '>' asm1/contigs.fa"
    - "shovill --outdir spades --assembler spades --R1 test/R1.fq.gz --R2 test/R2.fq.gz --ram 3 --cpus 0 --depth 25"
    - "grep '>' asm1/contigs.fa"
