language: perl

sudo: false

perl:
    - "5.14"

install:
    - ".travis/install_deps.sh" 
    - "export PATH=.:$PATH"

script:
    - "shovill --help"
    - "shovill --version"
    - "! shovill --doesnotexist"
