language: perl

sudo: false

perl:
    - "5.14"

install:
    - "source .travis/install_deps.sh" 
    - "export PATH=.:$PATH"
    - "echo $PATH"
    - "pwd"

script:
    - "shovill --help"
    - "shovill --version"
    - "! shovill --doesnotexist"
